In [1]:
import numpy as np 

In [2]:
#Comprobar versión de Numpy.
print(np.__version__)

2.1.3


#### Creamos un array cualquiera

In [3]:
mi_array = np.array([1,2,3])
print(mi_array)
print(type(mi_array))

[1 2 3]
<class 'numpy.ndarray'>


### Dimensión 1

In [4]:
mi_array = np.array([1,3,5,7])
print(mi_array)

[1 3 5 7]


### Dimensión 2

In [5]:
mi_array = np.array([[1,3,5,7],[1,2,3,4]])
print(mi_array)

[[1 3 5 7]
 [1 2 3 4]]


### Dimensión 3

In [6]:
mi_array = np.array([[[1,3,5,7],[1,2,3,4]],[[2,4,6,8],[9,7,5,3]]])
print(mi_array)

[[[1 3 5 7]
  [1 2 3 4]]

 [[2 4 6 8]
  [9 7 5 3]]]


### Creación de arrays de cualquier dimensión.

In [7]:
#Array de 5 dimensiones
mi_array = np.array([1,2,3], ndmin=5)
print(mi_array)

[[[[[1 2 3]]]]]


In [8]:
#Comprobar el número de dimensiones
mi_array.ndim

5

### Indexado de arrays.

In [9]:
mi_array = np.array([1,2,3,4])
print(mi_array[1])

2


In [10]:
mi_array = np.array([[1,3,5,7],[1,2,3,4]])
print(mi_array[1,1])

2


In [11]:
mi_array = np.array([[[1,3,5,7],[1,2,3,4]],[[2,4,6,8],[9,7,5,3]]])
print(mi_array[0,])

[[1 3 5 7]
 [1 2 3 4]]


In [ ]:
#Nos quedamos con los valores que queremos.
print(mi_array[1,1,1])


7


In [16]:
mi_array = np.array([100,300,500,700,900,1100,1300,1,2])
print(mi_array[3:7:2])
print(mi_array[3:7])
print(mi_array[3:-1])

[ 700 1100]
[ 700  900 1100 1300]
[ 700  900 1100 1300    1]


### Métodos Copy y View.

In [21]:
#Copy no sobrescribe los datos de la variable nueva.
mi_array = np.array([1,2,3,4,5,6,7,8])
mi_nuevo_array = mi_array.copy()

mi_array[1] = 100

print(mi_array)
print(mi_nuevo_array)

[  1 100   3   4   5   6   7   8]
[1 2 3 4 5 6 7 8]


In [22]:
#View si sobreescribe los datos de la variable nueva.
mi_array = np.array([1,2,3,4,5,6,7,8])
mi_nuevo_array = mi_array.view()

mi_array[1] = 100

print(mi_array)
print(mi_nuevo_array)

[  1 100   3   4   5   6   7   8]
[  1 100   3   4   5   6   7   8]


### Shape de un array.

In [24]:
mi_array = np.array([[[1,3,5,7],[1,2,3,4]],[[2,4,6,8],[9,7,5,3]]])

In [26]:
#Shape muestra las dimensiones de un array.
mi_array.shape

(2, 2, 4)

In [27]:
mi_array = np.array([1,2,3,4,5,6,7,8,9])
print(mi_array)
mi_nuevo_array = mi_array.reshape(3,3)
print(mi_nuevo_array)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Recorrido de arrays

In [35]:
mi_array = np.array([1,2,3,4,5,6,7,8,9])
for elemento in mi_array:
    print(elemento)

1
2
3
4
5
6
7
8
9


In [34]:
#Recorridos de distintas dimensiones.
mi_array = np.array([[1,2,3,4],[5,6,7,8]])
for fila in mi_array:
    for elemento in fila:
        print(elemento)

1
2
3
4
5
6
7
8


In [38]:
#Dimensiones más grandes
mi_array = np.array([[[1,3,5,7],[1,2,3,4]],[[2,4,6,8],[9,7,5,3]]])
for matriz in mi_array:
    for fila in matriz:
        for elemento in fila:
            print(elemento)

1
3
5
7
1
2
3
4
2
4
6
8
9
7
5
3


In [39]:
#Nos quedamos con los datos que queramos
for matriz in mi_array:
    for fila in matriz:
        print(fila)

[1 3 5 7]
[1 2 3 4]
[2 4 6 8]
[9 7 5 3]
