In [1]:
import numpy as np

### Unión de arrays.

In [5]:
ma_01 = np.array([1,2,3])
ma_02 = np.array([4,5,6])

#Utilizamos dos arrays para generar un array uniendo los dos arrays anteriores.
ma_t = np.concatenate((ma_01, ma_02))
print(ma_t)
#El orden depende de como lo pongamos en la funcion concatenate.
ma_t1 = np.concatenate((ma_02, ma_01))
print(ma_t1)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [17]:
ma_03 = np.array([[4,5,6],[1,2,3]])
ma_04 = np.array([[8,9,10],[11,12,13]])
ma_t3 = np.concatenate((ma_03, ma_04), axis=1)
ma_t4 = np.concatenate((ma_03, ma_04), axis=0)
#Axis une los arrays juntados las filas. Por ejemplo, si Axis es 1, junta las primeras filas de ambas matrices en 1. Axis tiene como máximo n-1, siendo n el numero de dimensiones.
#print(ma_03)
#print(ma_04)
print(ma_t3)
print(ma_t4)

[[ 4  5  6  8  9 10]
 [ 1  2  3 11 12 13]]
[[ 4  5  6]
 [ 1  2  3]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
mi_array = np.array([[[1,3,5,7],[1,2,3,4]],[[2,4,6,8],[9,7,5,3]]])