In [2]:
import numpy as np 
from numpy import random

### Random

Numeros enteros

In [4]:
numero = random.randint(10)
print(numero)

2


Numeros decimales

In [6]:
numero = random.rand()
numero

0.7209490450585925

Crear arrays con numeros aleatorios

In [9]:
# Crear arrays con valores enteros. El tamaño se define con size.
numero = random.randint(10, size=5)
array = random.randint(10, size=(5,2))
print(numero)
print(array)

[8 3 2 6 1]
[[7 0]
 [5 2]
 [3 4]
 [1 6]
 [1 9]]


In [10]:
# Podemos crear arrays con numeros decimales aleatorios, pero solo podran ser entre el 0 y el 1. Ponemos las dimensiones directamente.
ar_rand = random.rand(2,2)
print(ar_rand)

[[0.91097359 0.54686803]
 [0.69699285 0.27773009]]


Choice

In [13]:
# Escoge un valor aleatorio de una matriz.
numero = random.choice([1,2,3,4])
print(numero)

1


In [14]:
# También puede generar un array dado unos números y unas dimensiones.
array = random.choice([1,2,3,4], size=(2,3))
array

array([[4, 1, 1],
       [1, 4, 4]])

In [16]:
# Podemos asignarle pesos (p) para darle prioridad a ciertos numeros. 
arr = random.choice([4,3,2,1], p=[0.3,0.2,0.5,0], size=(3,3))
print(arr)

[[2 2 2]
 [2 4 4]
 [2 2 3]]


### Matemáticas

In [18]:
# Suma.
mi_array1 = np.array([4,2,3,4,5])
mi_array2 = np.array([1,3,2,7,2])
suma = np.add(mi_array1, mi_array2)
print(suma)

[ 5  5  5 11  7]


In [19]:
# Sum sumta todos los valores en uno.
resultado = np.sum(suma, axis=0)
print(f'Matriz sumada {suma}')
print(f'Resultado total {resultado}')

Matriz sumada [ 5  5  5 11  7]
Resultado total 33


In [25]:
# Axis suma según el eje escogido. Vemos que hay dos valores distintos de la misma suma.
ar = np.array([[1,2],[3,4]])
ar1 = np.array([[6,7],[8,9]])
suma = np.add(ar, ar1)
res = np.sum(suma, axis=1)
res1 = np.sum(suma, axis=0)
print(res)
print(res1)

[16 24]
[18 22]


In [26]:
# Resta.
mi_array1 = np.array([4,2,3,4,5])
mi_array2 = np.array([1,3,2,7,2])
resta = np.subtract(mi_array1,mi_array2)
print(resta)

[ 3 -1  1 -3  3]


In [27]:
# Multiplicación.
mi_array1 = np.array([4,2,3,4,5])
mi_array2 = np.array([1,3,2,7,2])
multi = np.multiply(mi_array1, mi_array2)
print(multi)

[ 4  6  6 28 10]


In [28]:
# Division
mi_array1 = np.array([4,2,3,4,5])
mi_array2 = np.array([1,3,2,7,2])
division = np.divide(mi_array1, mi_array2)
print(division)

[4.         0.66666667 1.5        0.57142857 2.5       ]


In [29]:
# Valor absoluto.
print(resta)
val_abs = np.absolute(resta)
print(val_abs)

[ 3 -1  1 -3  3]
[3 1 1 3 3]


In [31]:
# Aproximación en forma de truncamiento.
mi_array_dec = [-1.26, 4.89]
resultado = np.trunc(mi_array_dec)
print(resultado)

[-1.  4.]


In [32]:
# Aproximacion en forma de redondeo.
mi_array_dec2 = [-1.26, 4.89]
res2 = np.around(mi_array_dec2)
print(res2)

[-1.  5.]


In [33]:
# Aproximación hacia el valor más bajo.
res3 = np.floor(mi_array_dec2)
print(res3)

[-2.  4.]


In [34]:
# Aproximacion hacia el valor más alto.
res4 = np.ceil(mi_array_dec2)
print(res4)

[-1.  5.]
