In [2]:
import numpy as np
from numpy import random

### Actividades propuestas

1. Creación y manipulación de arrays
- Crea un array de números enteros del 1 al 10.
- Convierte este array en una matriz 2x5 y verifica su atributo shape.
- Cambia la forma de la matriz anterior a una matriz 5x2 usando reshape.

In [6]:
# Crear un array de numeros enteros del 1 al 10. 
ar = np.arange(1,11)
print(ar)

# Convertir este array en una matriz 2x5 y verificamos el shape.
ar1 = ar.reshape(2,5)
print(ar1)
print(f'Las dimensiones de la matriz son: {ar1.shape}.')

# Cambiamos la froma de la matriz al 5x2. 
ar2 = ar1.reshape(5,2)
print(ar2)
print(f'Las dimensiones de la matriz son: {ar2.shape}.')

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Las dimensiones de la matriz son: (2, 5).
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Las dimensiones de la matriz son: (5, 2).


2. Indexación y slicing
- Crea una matriz 4x4 con números aleatorios entre 0 y 20.
- Extrae:
    - La primera fila.
    - La última columna.
    - Los elementos en las posiciones [0,1], [2,3] y [3,0].
- Extrae los elementos de la matriz utilizando un rango y un paso, por ejemplo, columnas pares.

In [17]:
# Creamos matriz 4x4 con numeros aleatorios entre 0 y 20. 
mat = random.randint(0,20, size=(4,4))
print(mat)
# Extraemos la primera fila.
fila1 = mat[0]
print(fila1)
# Extraemos la ultima columna.
ult_col = mat[:,-1]
print(ult_col)
# Extraemos elementos concretos.
especificos = np.array([mat[0,1], mat[2,3], mat[3,0]])
print(especificos)
# Extraemos las columnas pares utilizando rango y paso.
col_par = mat[:,::2]
print(col_par)

[[18  5 13  8]
 [15  1 16 17]
 [ 0  3  0 17]
 [15 18  3  9]]
[18  5 13  8]
[ 8 17 17  9]
[ 5 17 15]
[[18 13]
 [15 16]
 [ 0  0]
 [15  3]]


3. Operaciones con arrays
- Crea dos arrays: uno de valores del 1 al 5 y otro del 6 al 10.
- Realiza las siguientes operaciones:
    - Suma.
    - Resta.
    - Multiplicación.
    - División.
- Aplica la función np.log al resultado de la suma.

In [20]:
# Creamos los dos arrays.
a1 = np.arange(1,6)
a2 = np.arange(6,11)

# Realizamos las operaciones.
suma = np.add(a1,a2)
resta = np.subtract(a1,a2)
multi = np.multiply(a1,a2)
division = np.divide(a1,a2)
print(f'La suma es {suma}.')
print(f'La resta es {resta}.')
print(f'La multiplicacion es {multi}.')
print(f'La división es {division}.')

# Aplicamos la funcion np.log a la suma. 
log = np.log(suma)
print(log)


La suma es [ 7  9 11 13 15].
La resta es [-5 -5 -5 -5 -5].
La multiplicacion es [ 6 14 24 36 50].
La división es [0.16666667 0.28571429 0.375      0.44444444 0.5       ].
[1.94591015 2.19722458 2.39789527 2.56494936 2.7080502 ]



4. Uso del módulo random
- Genera:
    - Un array de 10 números enteros aleatorios entre 0 y 50.
    - Una matriz 3x3 de números decimales aleatorios entre 0 y 1.
- Usa el método choice para seleccionar 5 elementos aleatorios de un array dado, alterando las probabilidades de selección.

In [29]:
# Generamos array de 10 enteros aleatorios entre 0 y 50.
rand_arr = random.randint(0,51, size=10)
print(rand_arr)

# Generamos matriz de 3x3 de numeros decimales aleatorios entre 0 y 1. 
rand_dec_arr = random.rand(3,3)
print(rand_dec_arr)

# Utilizamos metodo choice para seleccionar 5 elementos del array rand_arr, alterando sus pesos. Vamos a generar las probabilidades aleatoriamente.
prob = np.array([0.1,0.2,0.05,0.1,0.1,0.1,0.1,0.05,0.1,0.1])
choice = random.choice(rand_arr, p=prob, size=5)
print(choice)


[40 25  6 49 49 45 29 40 47 29]
[[0.46181345 0.32878028 0.4721253 ]
 [0.50748213 0.34506447 0.7928274 ]
 [0.598815   0.24736806 0.4334237 ]]
[45 29 47 49 25]


5. Manipulación de arrays
- Crea dos arrays bidimensionales (3x3) con valores consecutivos.
- Únelos:
    - En el eje 0.
    - En el eje 1.
- Divide uno de los arrays en 3 partes iguales.

6. Funciones adicionales
- Calcula:
    - La suma acumulativa de un array de números del 1 al 10.
    - El producto acumulativo del mismo array.
    - El logaritmo en base 2 de los valores obtenidos.
- Encuentra los valores únicos en un array con valores repetidos.