Importamos la librería.

In [1]:
import numpy as np

Actividad 1: Creación de Arrays.

Crea un array unidimensional con los números del 1 al 10.

Crea una matriz de 2x3 con los números del 1 al 6.

Verifica cuántas dimensiones tiene cada array.


In [11]:
# Array del 1 al 10.
array = np.arange(1,11)
print(array)
# Array de matriz 2x3 con 1 al 6
array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

# Dimensiones de cada array.
print(f'El primer array tiene unas dimensiones de {array.shape}.')
print(f'El segundo array tiene unas dimensiones de {array_2.shape}.')

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
El primer array tiene unas dimensiones de (10,).
El segundo array tiene unas dimensiones de (2, 3).


Actividad 2: Indexado y Slicing

Usa un array unidimensional para seleccionar el tercer elemento.

Extrae una submatriz de 2x2 de una matriz 3x3.

Experimenta con índices negativos para acceder a los últimos elementos de un array.


In [18]:
# Seleccionamos el tercer elemento del array unidimensional.
print(array[2])

#Extraemos una submatriz 2x2 de una 3x3.

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_ext = matriz[:2,:2]
print('La matriz original es:')
print(matriz)
print('La matriz extraida es:')
print(matriz_ext)
# Accedemos a los últimos índices de un array.
print(array[-1])
print(array[-2])
print(array[-3])

3
La matriz original es:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
La matriz extraida es:
[[1 2]
 [4 5]]
10
9
8
