Importamos la librería.

In [2]:
import numpy as np

Actividad 1: Creación de Arrays.

Crea un array unidimensional con los números del 1 al 10.

Crea una matriz de 2x3 con los números del 1 al 6.

Verifica cuántas dimensiones tiene cada array.


In [3]:
# Array del 1 al 10.
array = np.arange(1,11)
print(array)
# Array de matriz 2x3 con 1 al 6
array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

# Dimensiones de cada array.
print(f'El primer array tiene unas dimensiones de {array.shape}.')
print(f'El segundo array tiene unas dimensiones de {array_2.shape}.')

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
El primer array tiene unas dimensiones de (10,).
El segundo array tiene unas dimensiones de (2, 3).


Actividad 2: Indexado y Slicing

Usa un array unidimensional para seleccionar el tercer elemento.

Extrae una submatriz de 2x2 de una matriz 3x3.

Experimenta con índices negativos para acceder a los últimos elementos de un array.


In [4]:
# Seleccionamos el tercer elemento del array unidimensional.
print(array[2])

# Extraemos una submatriz 2x2 de una 3x3.
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_ext = matriz[:2,:2]
print('La matriz original es:')
print(matriz)
print('La matriz extraida es:')
print(matriz_ext)
# Accedemos a los últimos índices de un array.
print(array[-1])
print(array[-2])
print(array[-3])

3
La matriz original es:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
La matriz extraida es:
[[1 2]
 [4 5]]
10
9
8


Actividad 3: Métodos Copy y View

Crea un array y usa copy() para hacer una copia.

Modifica la copia y observa si afecta al array original.

Haz lo mismo con view() y compara los resultados.

In [8]:
# Creamos un array y hacemos una copia en otro array.
array = np.array([1,2,3,4,5])
array2 = array.copy()
print(array)
print(array2)
# Modificamos la copia y comprobamos que no modifica el array original.
array2[4] = 234
print(array)
print(array2)

# Realizamos las mismas operaciones con view.
array3 = np.array([1,2,3,4,5,6,7])
nuevoarray = array3.view()
print(array3)
print(nuevoarray)
array3[3] = 785
print(array3)
print(nuevoarray)


[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[  1   2   3   4 234]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[  1   2   3 785   5   6   7]
[  1   2   3 785   5   6   7]


Actividad 4: Modificar el Shape

Crea un array unidimensional con 12 elementos y cámbialo a una matriz de 3x4.

Intenta cambiarlo a una matriz 5x2 y describe por qué no funciona.


In [16]:
# Creamos un array unidimensional con 12 elementos y cambiamos a matriz 3x4.
array = np.arange(1,13)
print(array)
array = array.reshape([3,4])
print(array)

# Intentamos cambiarlo a matriz 5x2.
# array = array.reshape([5,2])
# print(array)

# Encontramos error : cannot reshape array of size 12 into shape (5,2). Tiene 12 elementos para un array que necesita 10.

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Actividad 5: Iteración

Itera sobre un array unidimensional con un bucle for y muestra sus elementos.

Haz lo mismo con una matriz de 2x3, accediendo a cada elemento usando dos bucles anidados.


In [20]:
# Iteramos sobre un array unidimensional con un bucle for.
array = np.arange(10,51,10)
for el in array:
    print(el)

# Realizamos el mismo proceso con una matriz 2x3.
array = np.array([[1,2,3],[4,5,6]])
for fila in array:
    for elem in fila:
        print(elem)

10
20
30
40
50
1
2
3
4
5
6


Actividad 6: Unir y Separar Arrays

Crea dos arrays unidimensionales y únelos concatenándolos.

Divide un array de 10 elementos en 3 partes usando.


In [32]:
# Creamos dos arrays unidimensionales y los concatenamos.
ar1 = np.arange(1,7)
ar2 = np.arange(10,16)
array = np.concatenate((ar1, ar2))
print(ar1)
print(ar2)
print(array)

# Dividimos un array de 10 elementos en 3 partes.
ar10 = np.arange(1,11)
print(ar10)
division = np.array_split(ar10,3)
print(division)
for fila in division:
    print(fila)


[1 2 3 4 5 6]
[10 11 12 13 14 15]
[ 1  2  3  4  5  6 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[1 2 3 4]
[5 6 7]
[ 8  9 10]


Actividad 7: Generación de Números Aleatorios

Genera 5 números enteros aleatorios entre 0 y 20 con random.randint.

Genera una matriz de 3x3 con números decimales aleatorios entre 0 y 1 usando random.rand.

In [33]:
# Generamos 5 enteros entre 0 y 20.
enteros = np.random.randint(0,21,size=5)
print(enteros)

# Generamos matriz 3x3 con numeros decimales aleatorios entre 0 y 1.
matriz = np.random.rand(3,3)
print(matriz)

[ 4  3  3 15  3]
[[0.9003732  0.21106479 0.66732933]
 [0.01464984 0.51228958 0.72781957]
 [0.9538229  0.92775652 0.16590756]]


Actividad 8: Búsqueda de Elementos

Encontrar los índices de los elementos iguales a 5 en un array.

Usa una condición para buscar elementos mayores que 10 en un array.


In [39]:
# Encontrar los indices de los elementos iguales a 5 en un array.
array = np.array([1,2,3,5,4,6,5,7,8,9,5,6,5,4,7,5,3,4,5])
indices = np.where(array == 5)
print(indices)

# Usamos una condicion para buscar elementos mayores que 10 en un array.
array2 = np.array([11,4,6,78,45,1,2,9,87,5,67,93])
for el in array2:
    if el > 10:
        print(el)

(array([ 3,  6, 10, 12, 15, 18]),)
11
78
45
87
67
93


Actividad 9: Operaciones Matemáticas

Crea dos arrays de igual longitud y realiza suma, resta, multiplicación y división entre ellos.

Calcula el valor absoluto de un array con números negativos.


In [41]:
# Creamos 2 arrays de la misma longitud y realizamos las operaciones básicas entre ellos.
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
suma = arr1 + arr2 
resta1 = arr2 - arr1 
resta2 = arr1 - arr2 
mult = arr1 * arr2 
div = arr2 / arr1 
print(suma)
print(resta1)
print(resta2)
print(mult)
print(div)

# Aprovechamos el array resta2 para calcularle el valor absoluto.
vabs = np.abs(resta2)
print(vabs)

[[12 14 16 18 20]
 [22 24 26 28 30]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[11.          6.          4.33333333  3.5         3.        ]
 [ 2.66666667  2.42857143  2.25        2.11111111  2.        ]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
